[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
JACC = "0979c8fe-16a4-4796-9b82-89a9f10403ea"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
oneAPI = "8f75cd03-7ff8-4ecb-9b8f-daf728133b1b"

[compat]
JACC = "0.6"
